const clothes = [
  {
    id: 1,
    name: "SK-01",
    category: "undergarments",
    image: "images/sk-01-white.jpeg",
    color: "white",
    type: "sock",
    price: 20,
    year: 2025,
    description: "3 PACK MIDWEIGHT SOCK"
  },
  {
    id: 2,
    name: "SK-01",
    category: "undergarments",
    image: "images/sk-01-gray.jpeg",
    color: "gray",
    type: "sock",
    price: 20,
    year: 2025,
    description: "3 PACK MIDWEIGHT SOCK" 
    
  },
  {
    id: 3,
    name: "SK-01",
    category: "undergarments",
    image: "images/sk-01-black.jpeg",
    color: "black",
    type: "sock",
    price: 20,
    year: 2025,
    description: "3 PACK MIDWEIGHT SOCK"
  },
  {
    id: 4,
    name: "SP-01",
    category: "bottoms",
    image: "images/sp-01-white.jpeg",
    color: "white",
    type: "sweatpant",
    price: 40,
    year: 2025,
    description: "BAGGY STRAIGHT LEG SWEATPANT, TWO SIDE POCKETS, DRAWCORD AT INNER WAIST" 
  },
  {
    id: 5,
    name: "SP-01",
    category: "bottoms",
    image: "images/sp-01-charcoal.jpeg",
    color: "black",
    type: "sweatpant",
    price: 40,
    year: 2025,
    description: "BAGGY STRAIGHT LEG SWEATPANT, TWO SIDE POCKETS, DRAWCORD AT INNER WAIST" 
  },
  {
    id: 6,
    name: "SP-06",
    category: "bottoms",
    image: "images/sp-06-white.jpeg",
    color: "white",
    type: "sweatpant",
    price: 40,
    year: 2025,
    description: "SWEATPANTS WITH ELASTIC CUFF, TWO SIDE POCKETS, DRAWCORD AT INNER WAIST" 
  },
  {
    id: 7,
    name: "SP-06",
    category: "bottoms",
    image: "images/sp-06-charcoal.jpeg",
    color: "black",
    type: "sweatpant",
    price: 40,
    year: 2025,
    description: "SWEATPANTS WITH ELASTIC CUFF, TWO SIDE POCKETS, DRAWCORD AT INNER WAIST" 
  },
  {
    id: 8,
    name: "SP-08",
    category: "bottoms",
    image: "images/sp-08-gray.jpeg",
    color: "gray",
    type: "sweatpant",
    price: 40,
    year: 2025,
    description: "SWEATPANTS WITH ELASTIC CUFF, TWO SIDE POCKETS, DRAWCORD AT INNER WAIST" 
  },
  {
    id: 9,
    name: "SP-09",
    category: "bottoms",
    image: "images/sp-09-gray.jpeg",
    color: "gray",
    type: "sweatpant",
    price: 40,
    year: 2025,
    description: "BAGGY STRAIGHT LEG SWEATPANT, TWO SIDE POCKETS, DRAWCORD AT INNER WAIST" 
  },
  {
    id: 10,
    name:  "TS-01",
    category: "tops",
    image: "images/ts-01-white.jpeg",
    color: "white",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "BOXY FIT T-SHIRT,SEAMLESS DROP SHOULDER"
  },
  {
    id: 11,
    name: "TS-01",
    category: "tops",
    image: "images/ts-01-gray.jpeg",
    color: "gray",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "BOXY FIT T-SHIRT,SEAMLESS DROP SHOULDER"
  },
  {
    id: 12,
    name: "TS-01",
    category: "tops",
    image: "images/ts-01-black.jpeg",
    color: "black",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "BOXY FIT T-SHIRT,SEAMLESS DROP SHOULDER" 
  },
  {
    id: 13,
    name: "TS-02",
    category: "tops",
    image: "images/ts-02-white.jpeg",
    color: "white",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "SLIM FIT RAGLAN T-SHIRT"
  },
  {
    id: 14,
    name: "TS-02",
    category: "tops",
    image: "images/ts-02-black.jpeg",
    color: "black",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "SLIM FIT RAGLAN T-SHIRT"
  },
  {
    id: 15,
    name: "TS-03",
    category: "tops",
    image: "images/ts-03-black.jpeg",
    color: "black",
    type: "tshirt",
    price: 40,
    year: 2025,
    description: "3 PACK SHRUNKEN TEE" 
  },
  {
    id: 16,
    name: "TS-03",
    category: "tops",
    image: "images/ts-03-cream.jpeg",
    color: "white",
    type: "tshirt",
    price: 40,
    year: 2025,
    description: "3 PACK SHRUNKEN TEE" 
  },
  {
    id: 17,
    name: "TS-03",
    category: "tops",
    image: "images/ts-03-olive.jpeg",
    color: "green",
    type: "tshirt",
    price: 40,
    year: 2025,
    description: "3 PACK SHRUNKEN TEE" 
  },
  {
    id: 18,
    name: "TS-04",
    category: "tops",
    image: "images/ts-04-black.jpeg",
    color: "black",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "COTTON SPANDEX FITTED BABY TEE"
  },
  {
    id: 19,
    name: "TS-05",
    category: "tops",
    image: "images/ts-05-black.jpeg",
    color: "black",
    type: "tshirt",
    price: 40,
    year: 2025,
    description: "DOUBLE LAYER COMBO, DROP SHOULDER T-SHIRT"
  },
  {
    id: 20,
    name: "TS-07",
    category: "tops",
    image: "images/ts-07-white.jpeg",
    color: "white",
    type: "tshirt",
    price: 20,
    year: 2025,
    description: "BASE T-SHIRT, SET IN SLEVE"
  },
   {
    id: 21,
    name: "TS-07",
    category: "tops",
    image: "images/ts-07-black.jpeg",
    color: "black",
    type: "tshirt",
    price: 20,
    year: 2025
  },
  {
    id: 22,
    name: "HD-01",
    category: "outerwear",
    image: "images/hd-01-gray.jpeg",
    color: "gray",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "CLASSIC PULLOVER HOODIE, DRAWCORD AT HOOD, POCKET AT FRONT"
  },
   {
    id: 23,
    name: "HD-01",
    category: "outerwear",
    image: "images/hd-01-white.jpeg",
    color: "white",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "CLASSIC PULLOVER HOODIE, DRAWCORD AT HOOD, POCKET AT FRONT"
  },
   {
    id: 24,
    name: "HD-02",
    category: "outerwear",
    image: "images/hd-02-black.jpeg",
    color: "black",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "POLAR FLEECE ZIP HOODIE, POCKET AT FRONT"
  },
  {
    id: 25,
    name: "HD-03",
    category: "outerwear",
    image: "images/hd-03-Black.jpeg",
    color: "black",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "ZIP HOODIE, SEAMLESS DROP SHOULDER, ELASTIC CUFF AND HEM, POCKET AT FRONT"
  },
  {
    id: 26,
    name: "HD-10",
    category: "outerwear",
    image: "images/hd-10-gray.jpeg",
    color: "gray",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "ZIP FRONT SZNX HOODIE, SEAMLESS DROP SHOULDER"
  },
  {
    id: 27,
    name: "HD-10",
    category: "outerwear",
    image: "images/HD-10-Black.jpeg",
    color: "black",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "ZIP FRONT SZNX HOODIE, SEAMLESS DROP SHOULDER"
  },
  {
    id: 28,
    name: "HD-01",
    category: "outerwear",
    image: "images/HD-01-Black.jpeg",
    color: "black",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "CLASSIC PULLOVER HOODIE, DRAWCORD AT HOOD, POCKET AT FRONT"
  },
  {
    id: 29,
    name: "HD-04",
    category: "outerwear",
    image: "images/HD-04-blue.jpeg",
    color: "blue",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "ZIP HOODIE, 16 OZ BRUSHED FLEECE, PLASTIC ZIPPER, RIB CUFF AND WAIST"
  },
  {
    id: 30,
    name: "HD-04",
    category: "outerwear",
    image: "images/HD-04-gray.jpeg",
    color: "gray",
    type: "hoodie",
    price: 40,
    year: 2025,
    description: "ZIP HOODIE, 16 OZ BRUSHED FLEECE, PLASTIC ZIPPER, RIB CUFF AND WAIST"
  },
  {
    id: 31,
    name: "SH-01",
    category: "bottoms",
    image: "images/sh-01-black.jpeg",
    color: "black",
    type: "short",
    price: 20,
    year: 2025,
    description: "CLASSIC NYLON SHORT, ELASTIC WAIST, TWO SIDE POCKETS"
  },
  {
    id: 32,
    name: "SH-01",
    category: "bottoms",
    image: "images/sh-01-gray.jpeg",
    color: "gray",
    type: "short",
    price: 20,
    year: 2025,
    description: "CLASSIC NYLON SHORT, ELASTIC WAIST, TWO SIDE POCKETS"
  },
  {
    id: 33,
    name: "SH-06",
    category: "bottoms",
    image: "images/sh-06-black.jpeg",
    color: "black",
    type: "short",
    price: 20,
    year: 2025,
    description: "COTTON SPANDEX BOY SHORTS"
  },
  {
    id: 34,
    name: "WB-01",
    category: "outerwear",
    image: "images/WB-01-black.jpeg",
    color: "black",
    type: "windbreaker",
    price: 40,
    year: 2025,
    description: "HOODED ZIP FRONT WINDBREAKER, TWO SIDE POCKETS, ELASTIC CUFF AND HEM"
  },
  {
    id: 35,
    name: "WB-01",
    category: "outerwear",
    image: "images/WB-01-gray.jpeg",
    color: "gray",
    type: "windbreaker",
    price: 40,
    year: 2025,
    description: "HOODED ZIP FRONT WINDBREAKER, TWO SIDE POCKETS, ELASTIC CUFF AND HEM"
  },
  {
    id: 36,
    name: "WB-04",
    category: "outerwear",
    image: "images/WB-04-brown.jpeg",
    color: "brown",
    type: "windbreaker",
    price: 40,
    year: 2025,
    description: "WINDBREAKER, LIGHTWEIGHT RIPSTOP WINDBREAKER, UNLINED, ELASTIC CUFF AND BOTTOM"
  },
  {
    id: 37,
    name: "WB-04",
    category: "outerwear",
    image: "images/WB-04-olive.jpeg",
    color: "green",
    type: "windbreaker",
    price: 40,
    year: 2025,
    description: "WINDBREAKER, LIGHTWEIGHT RIPSTOP WINDBREAKER, UNLINED, ELASTIC CUFF AND BOTTOM"
  },
  {
    id: 38,
    name: "JC-01",
    category: "outerwear",
    image: "images/JC-01-Black.jpeg",
    color: "black",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "FAUX LEATHER HOODED JACKET, ZIP FRONT WITH COVERED PLACKET, ELASTIC CUFF AND HEM, TWO SIDE POCKETS"
  },
  {
    id: 39,
    name: "JC-04",
    category: "outerwear",
    image: "images/JC-04-green.jpeg",
    color: "green",
    type: "jacket",
    price: 80,
    year: 2025,
    description: "COTTON M65 JACKET, COTTON LINED, HOOD INSIDE COLLAR"
  },
  {
    id: 40,
    name: "JC-08",
    category: "outerwear",
    image: "images/JC-08-White.jpeg",
    color: "white",
    type: "jacket",
    price: 80,
    year: 2025,
    description: "BOMBER WITH FLEECE HOOD"
  },
  {
    id: 41,
    name: "JC-09",
    category: "outerwear",
    image: "images/JC-09-black.jpeg",
    color: "black",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "WORK JACKET, COTTON CANVAS JACKET, VINTAGE WASH PROCESSING"
  },
  {
    id: 42,
    name: "JC-09",
    category: "outerwear",
    image: "images/JC-09-cream.jpeg",
    color: "white",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "WORK JACKET, COTTON CANVAS JACKET, VINTAGE WASH PROCESSING"
  },
  {
    id: 43,
    name: "JC-10",
    category: "outerwear",
    image: "images/JC-10-BLACK.jpeg",
    color: "black",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "STAND COLLAR JACKET, ZIP FRONT CLOSURE, LINED WITH FLEECE, LINED COLLAR"
  },
  {
    id: 44,
    name: "JC-11",
    category: "outerwear",
    image: "images/JC-11-BLACK.jpeg",
    color: "black",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "COTTON CARGO JACKET, LINED WITH HOOD INSIDE COLLAR"
  },
  {
    id: 45,
    name: "JC-03",
    category: "outerwear",
    image: "images/jc-03-black.jpeg",
    color: "black",
    type: "jacket",
    price: 40,
    year: 2025,
    description: "ZIP FRONT POLAR FLEECE HOODIE, TWO SIDE POCKETS, ELASTIC CUFF AND HEM"
  },
  {
    id: 46,
    name: "JC-05",
    category: "outerwear",
    image: "images/jc-05-black.jpeg",
    color: "black",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "STAND COLLAR FAUX LEATHER JACKET, TWO SIDE POCKETS, ELASTIC BANDED CUFF AND WAIST"
  },
  {
    id: 47,
    name: "JC-07",
    category: "outerwear",
    image: "images/jc-07-black.jpeg",
    color: "black",
    type: "jacket",
    price: 60,
    year: 2025,
    description: "LEATHER BOMBER, FAUX LEATHER JACKET WITH ELASTIC CUFF AND BOTTOM"
  },
  {
    id: 48,
    name: "JC-08",
    category: "outerwear",
    image: "images/jc-08-black.jpeg",
    color: "black",
    type: "jacket",
    price: 80,
    year: 2025,
    description: "BOMBER WITH FLEECE HOOD"
  },
  {
    id: 49,
    name: "BP-01",
    category: "accessories",
    image: "images/BP-01-black.jpeg",
    color: "black",
    type: "backpack",
    price: 40,
    year: 2025,
    description: "WATER REPELLENT BACKPACK, CLIP ROLL TOP CLOSURE"
  },
  {
    id: 50,
    name: "BP-02",
    category: "accessories",
    image: "images/BP-02-black.jpeg",
    color: "black",
    type: "backpack",
    price: 40,
    year: 2025,
    description: "BACKPACK, DOUBLE ZIP CLOSURE, ADJUSTABLE PADDED STRAPS, INNER CONCEALED PADDED LAPTOP SLEEVE"
  },
  {
    id: 51,
    name: "SG-01",
    category: "accessories",
    image: "images/SG-01-black.jpeg",
    color: "black",
    type: "sunglass",
    price: 20,
    year: 2025,
    description: "ONE PIECE FRAMELESS BRACK WRAP SUNGLASSES, ADJUSTABLE CORD"
  },
  {
    id: 52,
    name: "SG-02",
    category: "accessories",
    image: "images/sg-02-black.jpeg",
    color: "black",
    type: "sunglass",
    price: 20,
    year: 2025,
    description: "SAFETY SUNGLASSES, TRANSPARENT, BLACK REMOVABLE CORD"
  },
  {
    id: 53,
    name: "SG-03",
    category: "accessories",
    image: "images/SG-03-BLACK.jpeg",
    color: "black",
    type: "sunglass",
    price: 20,
    year: 2025,
    description: "BLACK ACTATE FRAME SUNGLASSES, DARK GREY LENSES"
  },
  {
    id: 54,
    name: "HT-01",
    category: "accessories",
    image: "images/HT-01-Black.jpeg",
    color: "black",
    type: "hat",
    price: 20,
    year: 2025,
    description: "5 PANEL CAP, VELCRO ADJUSTABLE TAB AT BACK"
  },
  {
    id: 55,
    name: "HT-04",
    category: "accessories",
    image: "images/HT-04-black.jpeg",
    color: "black",
    type: "hat",
    price: 20,
    year: 2025,
    description: "BEANIE"
  },
  {
    id: 56,
    name: "HT-05",
    category: "accessories",
    image: "images/ht-05-black.jpeg",
    color: "black",
    type: "hat",
    price: 20,
    year: 2025,
    description: "RIB SKI MASK"
  },
  {
    id: 57,
    name: "PD-01",
    category: "shoes",
    image: "images/PD-01-black.jpeg",
    color: "black",
    type: "sneaker",
    price: 20,
    year: 2025,
    description: "KNITTED SNEAKER"
  },
  {
    id: 58,
    name: "HB-01",
    category: "shoes",
    image: "images/HB-01-black.jpeg",
    color: "black",
    type: "boot",
    price: 100,
    year: 2025,
    description: "KNEE HIGH RUBBER WEDGE BOOT"
  },
  {
    id: 59,
    name: "HL-01",
    category: "shoes",
    image: "images/HL-01-black.jpeg",
    color: "black",
    type: "heel",
    price: 60,
    year: 2025,
    description: "SCULPTURAL POINTY TOE MULE WITH MICROFIBER FOOTBED, LIGHTWEIGHT STRUCTURE"
  },
  {
    id: 60,
    name: "HL-02",
    category: "shoes",
    image: "images/HL-02-Black.jpeg",
    color: "black",
    type: "heel",
    price: 60,
    year: 2025,
    description: "SCULPTURAL OPEN TOE WEDGE WITH RUBBER GRIP BOTTOM, LIGHTWEIGHT STRUCTURE"
  },
  {
    id: 61,
    name: "HL-03",
    category: "shoes",
    image: "images/HL-03-Gray.jpeg",
    color: "gray",
    type: "heel",
    price: 60,
    year: 2025,
    description: "TRANSULCENT POINTY TOE WEDGE MULE"
  },
  {
    id: 62,
    name: "SL-01",
    category: "shoes",
    image: "images/SL-01-WHITE.jpeg",
    color: "white",
    type: "slide",
    price: 20,
    year: 2025,
    description: "MOLDED SLIP ON SHOE"
  },
  {
    id: 63,
    name: "SL-01",
    category: "shoes",
    image: "images/SL-01-GRAY.jpeg",
    color: "gray",
    type: "slide",
    price: 20,
    year: 2025,
    description: "MOLDED SLIP ON SHOE"
  },
  {
    id: 64,
    name: "SL-01",
    category: "shoes",
    image: "images/SL-01-black.jpeg",
    color: "black",
    type: "slide",
    price: 20,
    year: 2025,
    description: "MOLDED SLIP ON SHOE, LIGHTWEIGHT"
  },
  {
    id: 65,
    name: "SL-02",
    category: "shoes",
    image: "images/SL-02-black.jpeg",
    color: "black",
    type: "slide",
    price: 40,
    year: 2025,
    description: "MOLDED SLIP ON SHOE WITH CUSHIONING, LIGHTWEIGHT"
  },
  {
    id: 66,
    name: "SL-03",
    category: "shoes",
    image: "images/SL-03-BLACK.jpeg",
    color: "black",
    type: "boot",
    price: 100,
    year: 2025,
    description: "-"
  },
  {
    id: 67,
    name: "UW-02",
    category: "undergarments",
    image: "images/uw-01-black.jpeg",
    color: "black",
    type: "underwear",
    price: 20,
    year: 2025,
    description: "COTTON SPANDEX THONG TWO PACK"
  },
  {
    id: 68,
    name: "LG-01",
    category: "bottoms",
    image: "images/LG-01-black.jpeg",
    color: "black",
    type: "leggings",
    price: 40,
    year: 2025,
    description: "SHINY TRICOT FOOTED TIGHT"
  },
  {
    id: 69,
    name: "LG-04",
    category: "bottoms",
    image: "images/LG-04-black.jpeg",
    color: "black",
    type: "leggings",
    price: 40,
    year: 2025,
    description: "VELVET COTTON YOGA PANT"
  },
  {
    id: 70,
    name: "LG-13",
    category: "bottoms",
    image: "images/LG-13-black.jpeg",
    color: "black",
    type: "leggings",
    price: 40,
    year: 2025,
    description: "SHINY TRICOT LEGGING"
  },
  {
    id: 71,
    name: "LG-14",
    category: "bottoms",
    image: "images/LG-14-black.jpeg",
    color: "black",
    type: "leggings",
    price: 40,
    year: 2025,
    description: "COATED SCUBA CAPRI LEGGING"
  },
  {
    id: 72,
    name: "PT-03",
    category: "bottoms",
    image: "images/PT-03-black.jpeg",
    color: "black",
    type: "pants",
    price: 40,
    year: 2025,
    description: "BAGGY STRAIGHT LEG NYLON PANT, ELASTIC BANDED WAIST, TWO POCKETS AT SIDE"
  },
  {
    id: 73,
    name: "PT-04",
    category: "bottoms",
    image: "images/PT-04-Black.jpeg",
    color: "black",
    type: "pants",
    price: 40,
    year: 2025,
    description: "STRAIGHT LEG 5 POCKET PANT, VELCRO FLY AND CLOSURE, COATED NYLON"
  },
  {
    id: 74,
    name: "PT-05",
    category: "bottoms",
    image: "images/PT-05-black.jpeg",
    color: "black",
    type: "pants",
    price: 40,
    year: 2025,
    description: "COATED MENS BAGGY 5 POCKET PANT"
  },
  {
    id: 75,
    name: "PT-10",
    category: "bottoms",
    image: "images/PT-10-black.jpeg",
    color: "black",
    type: "pants",
    price: 40,
    year: 2025,
    description: "COATED SCUBA LOW RISE TROUSER PANT"
  },
  {
    id: 76,
    name: "BR-01",
    category: "undergarments",
    image: "images/BR-01-black.jpeg",
    color: "black",
    type: "bra",
    price: 20,
    year: 2025,
    description: "COTTON SPANDEX BRALETTE"
  },
  {
    id: 77,
    name: "BD-03",
    category: "tops",
    image: "images/BD-03-Black.jpeg",
    color: "black",
    type: "bodysuit",
    price: 20,
    year: 2025,
    description: "SHINY TRICOT ADJUSTABLE STRAP CAMI BODYSUIT"
  },
  {
    id: 78,
    name: "BD-04",
    category: "tops",
    image: "images/BD-04-black.jpeg",
    color: "black",
    type: "bodysuit",
    price: 40,
    year: 2025,
    description: "SHINY TRICOT FOOTED ADJUSTABLE STRAP JUMPSUIT"
  },
  {
    id: 79,
    name: "BD-10",
    category: "tops",
    image: "images/BD-10-black.jpeg",
    color: "black",
    type: "bodysuit",
    price: 40,
    year: 2025,
    description: "SHORT SLEEVE COTTON SPANDEX ROMPER"
  },
  {
    id: 80,
    name: "TT-02",
    category: "tops",
    image: "images/TT-02-Black.jpeg",
    color: "black",
    type: "tubetop",
    price: 20,
    year: 2025,
    description: "SHINY TRICOT LONG TUBE TOP"
  },
  {
    id: 81,
    name: "TT-04",
    category: "tops",
    image: "images/TT-04-Black.jpeg",
    color: "black",
    type: "tubetop",
    price: 20,
    year: 2025,
    description: "SHINY TRICOT TUBE TOP"
  },
  {
    id: 82,
    name: "TT-06",
    category: "tops",
    image: "images/TT-06-Black.jpeg",
    color: "black",
    type: "tanktop",
    price: 40,
    year: 2025,
    description: "3 PACK BASE TANK"
  },
  {
    id: 83,
    name: "YS-01",
    category: "shoes",
    image: "images/Chocolate.JPEG",
    color: "brown",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 84,
    name: "YS-01",
    category: "shoes",
    image: "images/black.jpeg",
    color: "black",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 85,
    name: "YS-01",
    category: "shoes",
    image: "images/blue.jpeg",
    color: "blue",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 86,
    name: "YS-01",
    category: "shoes",
    image: "images/chestnut.jpeg",
    color: "brown",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 87,
    name: "YS-01",
    category: "shoes",
    image: "images/cream.jpeg",
    color: "white",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 88,
    name: "YS-01",
    category: "shoes",
    image: "images/gray.jpeg",
    color: "gray",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 89,
    name: "YS-01",
    category: "shoes",
    image: "images/white.jpeg",
    color: "white",
    type: "slide",
    price: 20,
    year: 2025,
    description: "YEEZY SLIDE"
  },
  {
    id: 90,
    name: "BT-01",
    category: "accessories",
    image: "images/BT-01-black.jpeg",
    color: "black",
    type: "belt",
    price: 40,
    year: 2025,
    description: "LEATHER BELT, VELCRO SIZE ADJUSTMENT TAB"
  },
  {
    id: 91,
    name: "WH-01",
    category: "accessories",
    image: "images/WH-01-white.jpeg",
    color: "white",
    type: "hat",
    price: 20,
    year: 2025,
    description: "MILITARY CADET HAT, ADJUSTABLE TAB AT BACK"
  },
  {
    id: 92,
    name: "PK-01",
    category: "outerwear",
    image: "images/PK-01-BLACK.jpeg",
    color: "black",
    type: "parka",
    price: 100,
    year: 2025,
    description: "FAUX LEATHER HOODED PARKA, FAUX FUR HOOD, PUFF INSULATION PADDING, TWO SIDE POCKETS"
  },
  {
    id: 93,
    name: "PK-01",
    category: "outerwear",
    image: "images/PK-01-blue.jpeg",
    color: "green",
    type: "parka",
    price: 100,
    year: 2025,
    description: "FAUX FUR HOODED PARKA, PUFF INSULATION PADDING, TWO SIDE POCKETS"
  },
  {
    id: 94,
    name: "PK-01",
    category: "outerwear",
    image: "images/PK-01-camo.jpeg",
    color: "green",
    type: "parka",
    price: 100,
    year: 2025,
    description: "FAUX FUR HOODED PARKA, PUFF INSULATION PADDING, TWO SIDE POCKETS"
  },
  {
    id: 95,
    name: "PK-01",
    category: "outerwear",
    image: "images/PK-01-SNOW-CAMO.jpeg",
    color: "white",
    type: "parka",
    price: 100,
    year: 2025,
    description: "FAUX FUR HOODED PARKA, PUFF INSULATION PADDING, TWO SIDE POCKETS"
  },
  {
    id: 96,
    name: "WJ-01",
    category: "outerwear",
    image: "images/WJ-01-brown.jpeg",
    color: "brown",
    type: "jacket",
    price: 80,
    year: 2025,
    description: "WOMENS MOCK NECK FAUX FUR JACKET"
  },
  {
    id: 97,
    name: "WJ-02",
    category: "outerwear",
    image: "images/WJ-02-black.jpeg",
    color: "black",
    type: "jacket",
    price: 40,
    year: 2025,
    description: "FLEECE TRACK JACKET"
  },
  {
    id: 98,
    name: "BX-01",
    category: "undergarments",
    image: "images/BX-01-black.jpeg",
    color: "black",
    type: "underwear",
    price: 40,
    year: 2025,
    description: "3 PACK MENS BOXER BRIEFS, ELASTIC BANDED WAIST"
  },
  {
    id: 99,
    name: "GL-01",
    category: "accessories",
    image: "images/GL-01.jpeg",
    color: "black",
    type: "gloves",
    price: 20,
    year: 2025,
    description: "UTILITY GLOVES"
  },
  {
    id: 100,
    name: "BG-01",
    category: "accessories",
    image: "images/BG-01-black.jpeg",
    color: "black",
    type: "bag",
    price: 60,
    year: 2025,
    description: "FAUX LEATHER DUFFLE BAG, PADDED SHOULDER STRAP, INTERNAL POCKET"
  },
  {
    id: 101,
    name: "BG-02",
    category: "accessories",
    image: "images/BG-02-black.jpeg",
    color: "black",
    type: "bag",
    price: 60,
    year: 2025,
    description: "OVERSIZED DUFFLE"
  },
  {
    id: 101,
    name: "BG-03",
    category: "accessories",
    image: "images/BG-03-GREEN.jpeg",
    color: "green",
    type: "bag",
    price: 60,
    year: 2025,
    description: "CANVAS 48 HOUR DUFFLE BAG"
  },
  {
    id: 102,
    name: "WD-01",
    category: "bottoms",
    image: "images/WD-01-black.jpeg",
    color: "black",
    type: "pants",
    price: 40,
    year: 2025,
    description: "WORK DENIM, COTTON JEANS, STRAIGHT CUT FIT, ELASTIC WAIST BAND"
  },
  {
    id: 103,
    name: "WD-01",
    category: "bottoms",
    image: "images/WD-01-white.jpeg",
    color: "white",
    type: "pants",
    price: 40,
    year: 2025,
    description: "WORK DENIM, COTTON JEANS, STRAIGHT CUT FIT, ELASTIC WAIST BAND"
  },
  {
    id: 104,
    name: "WD-02",
    category: "bottoms",
    image: "images/WD-02-GRAY.jpeg",
    color: "gray",
    type: "pants",
    price: 40,
    year: 2025,
    description: "WORK DENIM, COTTON JEANS, STRAIGHT CUT FIT, ELASTIC WAIST BAND"
  },
  {
    id: 105,
    name: "WP-01",
    category: "bottoms",
    image: "images/WP-01-white.jpeg",
    color: "white",
    type: "pants",
    price: 40,
    year: 2025,
    description: "COTTON CANVAS PANT, VINTAGE WASH PROCESSING"
  },
  {
    id: 106,
    name: "WP-01",
    category: "bottoms",
    image: "images/WP-01-black.jpeg",
    color: "black",
    type: "pants",
    price: 40,
    year: 2025,
    description: "COTTON CANVAS PANT, VINTAGE WASH PROCESSING"
  },
  {
    id: 108,
    name: "BB-01",
    category: "outerwear",
    image: "images/BB-01-BLUE.JPEG",
    color: "blue",
    type: "bomber",
    price: 80,
    year: 2025,
    description: "BOMBER JACKET, TWO TONE NYLON REVERSIBLE, RIB CUFF AND WAIST"
  },
  {
    id: 109,
    name: "BB-01",
    category: "outerwear",
    image: "images/BB-01-BROWN.JPEG",
    color: "brown",
    type: "bomber",
    price: 80,
    year: 2025,
    description: "BOMBER JACKET, TWO TONE NYLON REVERSIBLE, RIB CUFF AND WAIST"
  },
  {
    id: 110,
    name: "BB-01",
    category: "outerwear",
    image: "images/BB-01-GREEN.JPEG",
    color: "green",
    type: "bomber",
    price: 80,
    year: 2025,
    description: "BOMBER JACKET, TWO TONE NYLON REVERSIBLE, RIB CUFF AND WAIST"
  },
  {
    id: 111,
    name: "BB-02",
    category: "outerwear",
    image: "images/BB-02-BLACK.JPEG",
    color: "black",
    type: "bomber",
    price: 80,
    year: 2025,
    description: "MOCK NECK BOMBER, COTTON SELF, COTTON LINING, RIB CUFFS AND BOTTOM"
  },
{
    id: 112,
    name: "RC-03",
    category: "outerwear",
    image: "images/RC-03-BLACK.JPEG",
    color: "black",
    type: "raincoat",
    price: 80,
    year: 2025,
    description: "RAINCOAT WITH CONCEALED HOOD, TWO SIDE POCKETS, SEAMLESS DROP SHOULDER"
  },
{
    id: 113,
    name: "RC-04",
    category: "outerwear",
    image: "images/RC-04-BLUE.JPEG",
    color: "blue",
    type: "raincoat",
    price: 60,
    year: 2025,
    description: "FULL LENGTH HOODED RAINCOAT, ZIP FRONT CLOSURE, WATERPROOF"
  },
  {
    id: 114,
    name: "LS-03",
    category: "tops",
    image: "images/LS-03-WHITE.jpeg",
    color: "white",
    type: "longsleeve",
    price: 20,
    year: 2025,
    description: "BASE LONG SLEEVE, SET IN SLEEVE"
  },
  {
    id: 115,
    name: "CT-01",
    category: "outerwear",
    image: "images/CT-01-green.jpeg",
    color: "green",
    type: "coat",
    price: 80,
    year: 2025,
    description: "LONG PADDED COAT, ZIPPED FRONT CLOSURE, FLAP OUTER POCKETS"
  },
  {
    id: 116,
    name: "BL-01",
    category: "shoes",
    image: "images/BL-01-BLACK.jpeg",
    color: "black",
    type: "sneaker",
    price: 80,
    year: 2025,
    description: "LOW TOP SLIP ON SNEAKER WITH FOAM MIDDLE SOLE"
  }
];


















